import type { ConceptSeed, ConfusionPairSeed } from "./types";

const BOOK = "pub725-course-book" as const;
const NOTES = "chapter-1-agency-notes" as const;
const AGENCY = ["IV"] as const;

function book(
  heading: string,
  printedPage: number,
  pdfPage: number,
): ConceptSeed["citations"][number] {
  return {
    documentSlug: BOOK,
    heading,
    printedPage,
    pdfPage,
    layer: "course_book",
  };
}

function notes(heading: string, pdfPage: number): ConceptSeed["citations"][number] {
  return {
    documentSlug: NOTES,
    heading,
    pdfPage,
    layer: "chapter_notes",
  };
}

/**
 * Chapter 1 concepts taken from ingested PUB725 / Chapter 1 notes headings.
 * Pages are from local inspection. No definitions are stored here.
 */
export const CHAPTER_1_CONCEPTS: readonly ConceptSeed[] = [
  {
    slug: "nature-of-agency",
    name: "The nature of the agency",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [book("THE NATURE OF THE AGENCY", 1, 5), notes("Nature of the Agency", 1)],
  },
  {
    slug: "licensee",
    name: "Licensee",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Licensee", 1, 5), notes("Licensee", 1)],
  },
  {
    slug: "broker",
    name: "Broker",
    chapterNumber: 1,
    group: "broker-definition",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [book("Broker", 2, 6), notes("Broker", 1)],
    prerequisites: ["licensee"],
  },
  {
    slug: "negotiation",
    name: "Negotiation",
    chapterNumber: 1,
    group: "broker-definition",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [notes("Negotiation", 2)],
    partOf: ["broker"],
  },
  {
    slug: "pattern-of-sales",
    name: "Pattern of sales",
    chapterNumber: 1,
    group: "broker-definition",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [notes("Pattern of Sales", 2)],
    partOf: ["broker"],
  },
  {
    slug: "shows-property",
    name: "Shows property",
    chapterNumber: 1,
    group: "broker-definition",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [notes("Shows Property", 3)],
    partOf: ["broker"],
  },
  {
    slug: "advertises-property",
    name: "Advertises property",
    chapterNumber: 1,
    group: "broker-definition",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [notes("Advertises Property", 3)],
    partOf: ["broker"],
  },
  {
    slug: "written-report-of-property-value",
    name: "Written report of property value",
    chapterNumber: 1,
    group: "broker-definition",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [notes("Issues a Written Report of Property Value", 3)],
    partOf: ["broker"],
  },
  {
    slug: "license-exceptions",
    name: "Who does not need a license",
    chapterNumber: 1,
    group: "broker-definition",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [
      book("Exceptions: Who Does Not Need a License?", 4, 8),
      notes("Exceptions: Who Does Not Need a License?", 5),
    ],
    prerequisites: ["broker"],
  },
  {
    slug: "firm",
    name: "Firm",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Firm", 4, 8), notes("Firm", 6)],
    prerequisites: ["broker"],
  },
  {
    slug: "salesperson",
    name: "Salesperson",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Salesperson", 4, 8), notes("Salesperson", 6)],
    prerequisites: ["licensee", "firm"],
  },
  {
    slug: "agent",
    name: "Agent",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Agent", 5, 9), notes("Agent", 6)],
    prerequisites: ["licensee"],
  },
  {
    slug: "client",
    name: "Client",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Client", 5, 9), notes("Client", 7)],
    prerequisites: ["agent"],
  },
  {
    slug: "customer",
    name: "Customer",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Customer", 6, 10), notes("Customer", 8)],
    prerequisites: ["agent"],
  },
  {
    slug: "principal-firm",
    name: "Principal firm",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Principal Firm", 5, 9), notes("Principal Firm", 8)],
    prerequisites: ["firm"],
  },
  {
    slug: "subagent",
    name: "Subagent",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Subagent", 6, 10), notes("Subagent", 8)],
    prerequisites: ["principal-firm"],
  },
  {
    slug: "fiduciary",
    name: "Fiduciary",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Fiduciary", 8, 12), notes("Fiduciary", 11)],
    prerequisites: ["agent"],
  },
  {
    slug: "cooperating-firm",
    name: "Cooperating firm",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Cooperating Firm", 8, 12), notes("Cooperating Firm", 11)],
    prerequisites: ["firm"],
  },
  {
    slug: "listing-firm",
    name: "Listing firm",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Listing Firm", 9, 13), notes("Listing Firm", 12)],
    prerequisites: ["firm", "client"],
  },
  {
    slug: "listing-licensee",
    name: "Listing licensee / listing agent",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("Listing Licensee/Listing Agent", 9, 13),
      notes("Listing Licensee/Listing Agent", 13),
    ],
    prerequisites: ["listing-firm", "licensee"],
  },
  {
    slug: "selling-firm",
    name: "Selling firm",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Selling Firm", 10, 14), notes("Selling Firm", 14)],
    prerequisites: ["subagent", "cooperating-firm"],
  },
  {
    slug: "selling-licensee",
    name: "Selling licensee / selling agent",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("Selling Licensee/Selling Agent", 10, 14),
      notes("Selling Licensee/Selling Agent", 15),
    ],
    prerequisites: ["selling-firm"],
  },
  {
    slug: "buyers-firm",
    name: "Buyer’s firm",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Buyer’s Firm", 11, 15), notes("Buyer’s Firm", 16)],
    prerequisites: ["firm", "client"],
  },
  {
    slug: "buyers-licensee",
    name: "Buyer’s licensee / buyer’s agent",
    chapterNumber: 1,
    group: "roles",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("Buyer’s Licensee/Buyer’s Agent", 11, 15),
      notes("Buyer’s Licensee/Buyer’s Agent", 17),
    ],
    prerequisites: ["buyers-firm"],
  },
  {
    slug: "single-agency",
    name: "Single agency",
    chapterNumber: 1,
    group: "models",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Single Agency", 7, 11), notes("Single Agency", 9)],
    prerequisites: ["client"],
  },
  {
    slug: "multiple-representation",
    name: "Multiple representation",
    chapterNumber: 1,
    group: "models",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Multiple Representation", 7, 11), notes("Multiple Representation", 9)],
    prerequisites: ["client"],
  },
  {
    slug: "multiple-representation-without-designated-agency",
    name: "Multiple representation without designated agency",
    chapterNumber: 1,
    group: "models",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [notes("Multiple Representation without Designated Agency", 10)],
    partOf: ["multiple-representation"],
    prerequisites: ["multiple-representation"],
  },
  {
    slug: "multiple-representation-with-designated-agency",
    name: "Multiple representation with designated agency",
    chapterNumber: 1,
    group: "models",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [notes("Multiple Representation with Designated Agency", 10)],
    partOf: ["multiple-representation"],
    prerequisites: ["multiple-representation"],
  },
  {
    slug: "seller-agency",
    name: "Seller agency",
    chapterNumber: 1,
    group: "models",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Seller Agency", 12, 16), notes("Seller Agency", 18)],
    prerequisites: ["listing-firm"],
  },
  {
    slug: "buyer-agency",
    name: "Buyer agency",
    chapterNumber: 1,
    group: "models",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Buyer Agency", 12, 16), notes("Buyer Agency", 19)],
    prerequisites: ["buyers-firm"],
  },
  {
    slug: "pre-agency",
    name: "Pre-agency",
    chapterNumber: 1,
    group: "models",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Pre-agency Stage", 14, 18), notes("Pre-agency Stage", 23)],
    prerequisites: ["licensee"],
  },
  {
    slug: "duties-to-all-persons",
    name: "Duties to all persons in a transaction",
    chapterNumber: 1,
    group: "duties",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("Duties to All Persons in a Transaction", 13, 17),
      notes("Duties to All Persons in a Transaction", 20),
    ],
    prerequisites: ["licensee"],
  },
  {
    slug: "material-adverse-fact",
    name: "Material adverse fact",
    chapterNumber: 1,
    group: "duties",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("Important Terminology", 1, 5),
      book("Duties to All Persons in a Transaction", 13, 17),
    ],
    partOf: ["duties-to-all-persons"],
  },
  {
    slug: "duties-owed-to-a-client",
    name: "Duties owed to a client",
    chapterNumber: 1,
    group: "duties",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Duties Owed to a Client", 15, 19), notes("Duties Owed to a Client", 24)],
    prerequisites: ["client", "duties-to-all-persons"],
  },
  {
    slug: "duties-for-subagents",
    name: "Duties for subagents",
    chapterNumber: 1,
    group: "duties",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Duties for Subagents", 16, 20), notes("Duties for Subagents", 26)],
    prerequisites: ["subagent", "duties-to-all-persons"],
  },
  {
    slug: "agency-disclosure-obligations",
    name: "Agency disclosure obligations",
    chapterNumber: 1,
    group: "disclosure",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [
      book("AGENCY DISCLOSURE OBLIGATIONS", 16, 20),
      notes("Agency Disclosure Obligations", 26),
    ],
    prerequisites: ["client", "customer"],
  },
  {
    slug: "customer-agency-disclosure",
    name: "Customer agency disclosure",
    chapterNumber: 1,
    group: "disclosure",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("Customer Agency Disclosure Obligations", 16, 20),
      notes("Customer Agency Disclosure Obligations", 26),
    ],
    partOf: ["agency-disclosure-obligations"],
    prerequisites: ["customer"],
  },
  {
    slug: "client-agency-disclosure",
    name: "Client agency disclosure",
    chapterNumber: 1,
    group: "disclosure",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [
      book("Client Agency Disclosure Obligations", 17, 21),
      notes("Client Agency Disclosure Obligations", 27),
    ],
    partOf: ["agency-disclosure-obligations"],
    prerequisites: ["client"],
  },
  {
    slug: "providing-agency-disclosure",
    name: "Providing agency disclosure",
    chapterNumber: 1,
    group: "disclosure",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("Providing Agency Disclosure", 18, 22),
      notes("Providing Agency Disclosure", 29),
    ],
    partOf: ["agency-disclosure-obligations"],
  },
  {
    slug: "acknowledgement-of-agency-disclosure",
    name: "Acknowledgement of agency disclosure",
    chapterNumber: 1,
    group: "disclosure",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("Acknowledgement of Agency Disclosure", 18, 22),
      notes("Acknowledgement of Agency Disclosure", 29),
    ],
    partOf: ["agency-disclosure-obligations"],
  },
  {
    slug: "additional-disclosure-by-buyers-firm",
    name: "Additional disclosure obligation by buyer’s firm",
    chapterNumber: 1,
    group: "disclosure",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("Additional Disclosure Obligation by Buyer’s Firm", 18, 22),
      notes("Additional Disclosure Obligation by Buyer’s Firm", 30),
    ],
    prerequisites: ["buyers-firm"],
  },
  {
    slug: "disclosure-of-compensation-and-interests",
    name: "Disclosure of compensation and interests",
    chapterNumber: 1,
    group: "disclosure",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [
      book("DISCLOSURE OF COMPENSATION AND INTERESTS", 19, 23),
      notes("Disclosure of Compensation and Interests", 30),
    ],
    prerequisites: ["licensee"],
  },
  {
    slug: "personal-assistants",
    name: "Personal assistants",
    chapterNumber: 1,
    group: "office",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Personal Assistants", 21, 25), notes("Personal Assistants", 35)],
    prerequisites: ["firm"],
  },
  {
    slug: "unlicensed-personal-assistant",
    name: "Unlicensed personal assistant",
    chapterNumber: 1,
    group: "office",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [notes("Unlicensed Personal Assistant", 35)],
    partOf: ["personal-assistants"],
  },
  {
    slug: "licensed-personal-assistant",
    name: "Licensed personal assistant",
    chapterNumber: 1,
    group: "office",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [notes("Licensed Personal Assistant", 35)],
    partOf: ["personal-assistants"],
  },
  {
    slug: "dsps-notification",
    name: "Notifying DSPS",
    chapterNumber: 1,
    group: "office",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [
      book("Notifying the Department of Safety and Professional Services (DSPS)", 22, 26),
      notes("Notifying the Department of Safety and Professional Services (DSPS)", 35),
    ],
    prerequisites: ["licensee"],
  },
];

export const CHAPTER_1_CONFUSION_PAIRS: readonly ConfusionPairSeed[] = [
  {
    a: "client",
    b: "customer",
    reason: "Chapter 1 lists these as separate terms; they are not interchangeable.",
  },
  {
    a: "multiple-representation",
    b: "multiple-representation-with-designated-agency",
    reason: "Designated agency is a form of multiple representation, not a separate agency model from the chapter headings.",
  },
  {
    a: "multiple-representation-without-designated-agency",
    b: "multiple-representation-with-designated-agency",
    reason: "Chapter 1 notes split multiple representation into with vs without designated agency.",
  },
  {
    a: "listing-firm",
    b: "selling-firm",
    reason: "Chapter 1 headings distinguish the listing firm from the selling firm.",
  },
  {
    a: "listing-licensee",
    b: "selling-licensee",
    reason: "Chapter 1 headings distinguish listing licensee/agent from selling licensee/agent.",
  },
  {
    a: "listing-licensee",
    b: "buyers-licensee",
    reason: "Chapter 1 headings distinguish the listing licensee from the buyer’s licensee.",
  },
  {
    a: "selling-firm",
    b: "buyers-firm",
    reason: "Chapter 1 headings distinguish a selling firm from a buyer’s firm.",
  },
  {
    a: "duties-to-all-persons",
    b: "duties-owed-to-a-client",
    reason: "Chapter 1 separates duties owed to all persons from extra duties owed to a client.",
  },
  {
    a: "customer-agency-disclosure",
    b: "client-agency-disclosure",
    reason: "Chapter 1 has separate customer and client agency disclosure headings.",
  },
  {
    a: "unlicensed-personal-assistant",
    b: "licensed-personal-assistant",
    reason: "Chapter 1 notes split personal assistants into licensed vs unlicensed.",
  },
];

/** Locked pairs that wait until later chapters exist as concepts. */
export const DEFERRED_CONFUSION_PAIRS: readonly ConfusionPairSeed[] = [
  { a: "appraised-value", b: "assessed-value", reason: "Not in Chapter 1 headings." },
  { a: "easement", b: "license", reason: "Not in Chapter 1 headings." },
  { a: "exclusive-agency", b: "exclusive-right-to-sell", reason: "Not in Chapter 1 headings." },
];

export const WI_SCOPED_CHAPTER_1_SLUGS = CHAPTER_1_CONCEPTS.filter(
  (concept) => concept.jurisdictionScope === "wi",
).map((concept) => concept.slug);
