import type { ConceptSeed, ConfusionPairSeed } from "./types";

const BOOK = "pub725-course-book" as const;
const NOTES = "chapter-2-agency-issues-notes" as const;
const AGENCY = ["IV"] as const;
const ANTITRUST = ["IX"] as const;

function book(
  heading: string,
  printedPage: number,
  pdfPage: number,
): ConceptSeed["citations"][number] {
  return {
    documentSlug: BOOK,
    heading,
    printedPage,
    pdfPage,
    layer: "course_book",
  };
}

function notes(heading: string, pdfPage: number): ConceptSeed["citations"][number] {
  return {
    documentSlug: NOTES,
    heading,
    pdfPage,
    layer: "chapter_notes",
  };
}

/**
 * Chapter 2 concepts from PUB725 / Chapter 2 notes headings.
 * Pages from local inspection. No definitions stored here.
 */
export const CHAPTER_2_CONCEPTS: readonly ConceptSeed[] = [
  {
    slug: "creation-of-agency",
    name: "The creation of agency",
    chapterNumber: 2,
    group: "agency-creation",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [book("THE CREATION OF AGENCY", 27, 31), notes("The Creation of Agency", 1)],
    prerequisites: ["agent"],
  },
  {
    slug: "express-agency",
    name: "Express agency",
    chapterNumber: 2,
    group: "agency-creation",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [book("Important Terminology", 27, 31), notes("The Creation of Agency", 1)],
    partOf: ["creation-of-agency"],
    prerequisites: ["creation-of-agency"],
  },
  {
    slug: "implied-agency",
    name: "Implied agency",
    chapterNumber: 2,
    group: "agency-creation",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [book("Important Terminology", 27, 31), notes("The Creation of Agency", 1)],
    partOf: ["creation-of-agency"],
    prerequisites: ["creation-of-agency"],
  },
  {
    slug: "types-of-agency-contracts",
    name: "Types of agency contracts",
    chapterNumber: 2,
    group: "agency-contracts",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("TYPES OF AGENCY CONTRACTS", 29, 33), notes("Types of Agency Contracts", 3)],
    prerequisites: ["creation-of-agency"],
  },
  {
    slug: "special-agency",
    name: "Special agency",
    chapterNumber: 2,
    group: "agency-contracts",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("TYPES OF AGENCY CONTRACTS", 29, 33), book("Important Terminology", 27, 31)],
    partOf: ["types-of-agency-contracts"],
  },
  {
    slug: "general-agency",
    name: "General agency",
    chapterNumber: 2,
    group: "agency-contracts",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("TYPES OF AGENCY CONTRACTS", 29, 33), book("Important Terminology", 27, 31)],
    partOf: ["types-of-agency-contracts"],
  },
  {
    slug: "listing-contracts",
    name: "Listing contracts",
    chapterNumber: 2,
    group: "agency-contracts",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Listing Contracts", 29, 33), notes("Listing Contracts", 4)],
    prerequisites: ["listing-firm", "types-of-agency-contracts"],
  },
  {
    slug: "exclusive-right-to-sell-listing",
    name: "Exclusive right to sell listing contract",
    chapterNumber: 2,
    group: "agency-contracts",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("Listing Contracts", 29, 33),
      book("Important Terminology", 27, 31),
      notes("Exclusive Right to Sell Listing Contract", 4),
    ],
    partOf: ["listing-contracts"],
    prerequisites: ["listing-contracts"],
  },
  {
    slug: "exclusive-agency-listing",
    name: "Exclusive agency listing contract",
    chapterNumber: 2,
    group: "agency-contracts",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("Important Terminology", 27, 31),
      notes("Exclusive Agency Listing Contract", 5),
    ],
    partOf: ["listing-contracts"],
    prerequisites: ["listing-contracts"],
  },
  {
    slug: "open-listing-contract",
    name: "Open listing contract",
    chapterNumber: 2,
    group: "agency-contracts",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Important Terminology", 27, 31), notes("Open Listing Contract", 5)],
    partOf: ["listing-contracts"],
    prerequisites: ["listing-contracts"],
  },
  {
    slug: "one-party-listing-contract",
    name: "One-party listing contract",
    chapterNumber: 2,
    group: "agency-contracts",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Important Terminology", 27, 31), notes("One-party Listing Contract", 5)],
    partOf: ["listing-contracts"],
    prerequisites: ["listing-contracts"],
  },
  {
    slug: "net-listing-contract",
    name: "Net listing contract",
    chapterNumber: 2,
    group: "agency-contracts",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Important Terminology", 27, 31), notes("Net Listing Contract", 6)],
    partOf: ["listing-contracts"],
    prerequisites: ["listing-contracts"],
  },
  {
    slug: "buyer-agency-agreements",
    name: "Buyer agency agreements",
    chapterNumber: 2,
    group: "agency-contracts",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Buyer Agency Agreements", 30, 34), notes("Buyer Agency Agreements", 6)],
    prerequisites: ["buyers-firm", "types-of-agency-contracts"],
  },
  {
    slug: "exclusive-right-to-locate",
    name: "Exclusive right to locate",
    chapterNumber: 2,
    group: "agency-contracts",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [notes("Exclusive Right to Locate", 6), book("Buyer Agency Agreements", 30, 34)],
    partOf: ["buyer-agency-agreements"],
    prerequisites: ["buyer-agency-agreements"],
  },
  {
    slug: "exclusive-right-to-negotiate",
    name: "Exclusive right to negotiate",
    chapterNumber: 2,
    group: "agency-contracts",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [notes("Exclusive Right to Negotiate", 6), book("Buyer Agency Agreements", 30, 34)],
    partOf: ["buyer-agency-agreements"],
    prerequisites: ["buyer-agency-agreements"],
  },
  {
    slug: "exclusive-right-to-locate-and-negotiate",
    name: "Exclusive right to locate and negotiate",
    chapterNumber: 2,
    group: "agency-contracts",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      notes("Exclusive Right to Locate and Negotiate", 6),
      book("Buyer Agency Agreements", 30, 34),
    ],
    partOf: ["buyer-agency-agreements"],
    prerequisites: ["buyer-agency-agreements"],
  },
  {
    slug: "termination-of-agency",
    name: "Termination of agency",
    chapterNumber: 2,
    group: "termination",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("TERMINATION OF AGENCY", 31, 35), notes("Termination of Agency", 7)],
    prerequisites: ["creation-of-agency"],
  },
  {
    slug: "remedies-for-breach",
    name: "Remedies for breach of an agency agreement",
    chapterNumber: 2,
    group: "remedies",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("REMEDIES FOR BREACH OF AN AGENCY AGREEMENT", 32, 36),
      notes("Remedies for Breach of an Agency Agreement", 8),
    ],
    prerequisites: ["types-of-agency-contracts"],
  },
  {
    slug: "damages",
    name: "Damages",
    chapterNumber: 2,
    group: "remedies",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Important Terminology", 27, 31), notes("Remedies for Breach of an Agency Agreement", 8)],
    partOf: ["remedies-for-breach"],
  },
  {
    slug: "rescission",
    name: "Rescission",
    chapterNumber: 2,
    group: "remedies",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Important Terminology", 27, 31), notes("Remedies for Breach of an Agency Agreement", 8)],
    partOf: ["remedies-for-breach"],
  },
  {
    slug: "commission",
    name: "Commission",
    chapterNumber: 2,
    group: "compensation",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("COMMISSION", 32, 36), notes("Commission", 9)],
    prerequisites: ["listing-contracts"],
  },
  {
    slug: "ready-willing-and-able-buyer",
    name: "Ready, willing, and able buyer",
    chapterNumber: 2,
    group: "compensation",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Important Terminology", 27, 31), book("PAYMENT OF A LISTING FIRM", 39, 43)],
    prerequisites: ["commission"],
  },
  {
    slug: "antitrust-laws",
    name: "Antitrust laws",
    chapterNumber: 2,
    group: "antitrust",
    jurisdictionScope: "wi",
    examCategoryCodes: ANTITRUST,
    citations: [book("Antitrust Laws", 32, 36), notes("Antitrust Laws", 9)],
    prerequisites: ["commission"],
  },
  {
    slug: "price-fixing",
    name: "Price fixing",
    chapterNumber: 2,
    group: "antitrust",
    jurisdictionScope: "both",
    examCategoryCodes: ANTITRUST,
    citations: [book("Antitrust Laws", 32, 36), book("Important Terminology", 27, 31)],
    partOf: ["antitrust-laws"],
  },
  {
    slug: "group-boycott",
    name: "Group boycott",
    chapterNumber: 2,
    group: "antitrust",
    jurisdictionScope: "both",
    examCategoryCodes: ANTITRUST,
    citations: [book("Important Terminology", 27, 31), notes("Antitrust Laws", 9)],
    partOf: ["antitrust-laws"],
  },
  {
    slug: "fee-splitting",
    name: "Fee-splitting",
    chapterNumber: 2,
    group: "compensation",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Important Terminology", 27, 31), book("Other Commission Issues", 33, 37)],
    prerequisites: ["commission"],
  },
  {
    slug: "other-commission-issues",
    name: "Other commission issues",
    chapterNumber: 2,
    group: "compensation",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [book("Other Commission Issues", 33, 37), notes("Other Commission Issues", 11)],
    prerequisites: ["commission"],
  },
  {
    slug: "dividing-commissions",
    name: "Dividing commissions",
    chapterNumber: 2,
    group: "compensation",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Dividing Commissions", 34, 38), notes("Dividing Commissions", 11)],
    prerequisites: ["commission"],
  },
  {
    slug: "commission-cooperating-firms",
    name: "Commission in a sale with cooperating firms",
    chapterNumber: 2,
    group: "compensation",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("Commission in a Sale with Cooperating Firms", 34, 38),
      notes("Commission in a Sale with Cooperating Firms", 12),
    ],
    prerequisites: ["cooperating-firm", "commission"],
  },
  {
    slug: "commission-in-house-sale",
    name: "Commission in an in-house sale",
    chapterNumber: 2,
    group: "compensation",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [
      book("Commission in an In-House Sale", 35, 39),
      notes("Commission in an In-House Sale", 13),
    ],
    prerequisites: ["commission", "multiple-representation"],
  },
  {
    slug: "in-house-sale",
    name: "In-house sale",
    chapterNumber: 2,
    group: "compensation",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Important Terminology", 27, 31), book("Commission in an In-House Sale", 35, 39)],
    prerequisites: ["multiple-representation"],
  },
  {
    slug: "calculating-commissions",
    name: "Calculating commissions",
    chapterNumber: 2,
    group: "compensation",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("CALCULATING COMMISSIONS", 36, 40), notes("Calculating Commission", 14)],
    prerequisites: ["commission"],
  },
  {
    slug: "payment-of-listing-firm",
    name: "Payment of a listing firm",
    chapterNumber: 2,
    group: "compensation",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [book("PAYMENT OF A LISTING FIRM", 39, 43), notes("Payment of Listing Firm", 17)],
    prerequisites: ["listing-firm", "commission", "ready-willing-and-able-buyer"],
  },
  {
    slug: "payment-of-buyers-firm",
    name: "Payment of a buyer’s firm",
    chapterNumber: 2,
    group: "compensation",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY,
    citations: [book("PAYMENT OF A BUYER’S FIRM", 39, 43), notes("Payment of Buyer's Firm", 18)],
    prerequisites: ["buyers-firm", "commission"],
  },
  {
    slug: "mirror-image-offer",
    name: "Mirror image offer",
    chapterNumber: 2,
    group: "compensation",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("Important Terminology", 27, 31)],
    prerequisites: ["payment-of-listing-firm"],
  },
];

export const CHAPTER_2_CONFUSION_PAIRS: readonly ConfusionPairSeed[] = [
  {
    a: "express-agency",
    b: "implied-agency",
    reason: "Chapter 2 Important Terminology lists express agency and implied agency as separate creation paths.",
  },
  {
    a: "exclusive-agency-listing",
    b: "exclusive-right-to-sell-listing",
    reason: "Chapter 2 notes list exclusive agency and exclusive right to sell as separate listing contract headings.",
  },
  {
    a: "open-listing-contract",
    b: "exclusive-right-to-sell-listing",
    reason: "Chapter 2 notes distinguish an open listing from an exclusive right to sell listing.",
  },
  {
    a: "special-agency",
    b: "general-agency",
    reason: "Chapter 2 Important Terminology and Types of Agency Contracts treat special and general agency as separate terms.",
  },
  {
    a: "listing-contracts",
    b: "buyer-agency-agreements",
    reason: "Chapter 2 has separate headings for listing contracts and buyer agency agreements.",
  },
  {
    a: "exclusive-right-to-locate",
    b: "exclusive-right-to-negotiate",
    reason: "Chapter 2 notes split buyer agency into locate vs negotiate authority headings.",
  },
  {
    a: "damages",
    b: "rescission",
    reason: "Chapter 2 Important Terminology lists damages and rescission as separate remedy terms.",
  },
  {
    a: "price-fixing",
    b: "group-boycott",
    reason: "Chapter 2 Important Terminology lists price fixing and group boycott as separate antitrust terms.",
  },
  {
    a: "commission-cooperating-firms",
    b: "commission-in-house-sale",
    reason: "Chapter 2 has separate headings for cooperating-firm commission and in-house sale commission.",
  },
  {
    a: "payment-of-listing-firm",
    b: "payment-of-buyers-firm",
    reason: "Chapter 2 ends with separate payment headings for the listing firm and the buyer’s firm.",
  },
];

export const WI_SCOPED_CHAPTER_2_SLUGS = CHAPTER_2_CONCEPTS.filter(
  (concept) => concept.jurisdictionScope === "wi",
).map((concept) => concept.slug);
