import type { ConceptSeed, ConfusionPairSeed } from "./types";

const BOOK = "pub725-course-book" as const;
const NOTES = "chapter-3-agency-agreements-notes" as const;
const AGENCY = ["IV"] as const;
const FORMS = ["VI"] as const;
const AGENCY_AND_FORMS = ["IV", "VI"] as const;

function book(
  heading: string,
  printedPage: number,
  pdfPage: number,
): ConceptSeed["citations"][number] {
  return {
    documentSlug: BOOK,
    heading,
    printedPage,
    pdfPage,
    layer: "course_book",
  };
}

function notes(heading: string, pdfPage: number): ConceptSeed["citations"][number] {
  return {
    documentSlug: NOTES,
    heading,
    pdfPage,
    layer: "chapter_notes",
  };
}

/**
 * Chapter 3 concepts from PUB725 / Chapter 3 notes headings (Agency Agreements).
 * Pages from local inspection. No definitions stored here.
 */
export const CHAPTER_3_CONCEPTS: readonly ConceptSeed[] = [
  {
    slug: "real-estate-transaction",
    name: "The real estate transaction",
    chapterNumber: 3,
    group: "transaction",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [book("THE REAL ESTATE TRANSACTION", 43, 47), notes("The Real Estate Transaction", 1)],
    prerequisites: ["agent", "client"],
  },
  {
    slug: "buyer-in-transaction",
    name: "The buyer (in the transaction)",
    chapterNumber: 3,
    group: "transaction",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [notes("The buyer", 1), notes("Buyers", 4)],
    partOf: ["real-estate-transaction"],
  },
  {
    slug: "seller-in-transaction",
    name: "The seller (in the transaction)",
    chapterNumber: 3,
    group: "transaction",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [notes("The seller", 2), notes("Sellers", 4)],
    partOf: ["real-estate-transaction"],
  },
  {
    slug: "closing",
    name: "The closing",
    chapterNumber: 3,
    group: "transaction",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY,
    citations: [notes("The closing", 3)],
    partOf: ["real-estate-transaction"],
  },
  {
    slug: "agency-agreements",
    name: "Agency agreements",
    chapterNumber: 3,
    group: "agency-agreements",
    jurisdictionScope: "both",
    examCategoryCodes: AGENCY_AND_FORMS,
    citations: [book("AGENCY AGREEMENTS", 45, 49), notes("Agency Agreements", 4)],
    prerequisites: ["types-of-agency-contracts", "listing-contracts", "buyer-agency-agreements"],
  },
  {
    slug: "wb-1-residential-listing",
    name: "WB-1 Residential Listing Contract — Exclusive Right to Sell",
    chapterNumber: 3,
    group: "agency-agreements",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY_AND_FORMS,
    citations: [
      book("WB-1 RESIDENTIAL LISTING CONTRACT-EXCLUSIVE RIGHT TO SELL", 46, 50),
      notes("WB-1 Residential Listing Contract — Exclusive Right to Sell", 5),
    ],
    partOf: ["agency-agreements"],
    prerequisites: ["exclusive-right-to-sell-listing", "agency-agreements"],
  },
  {
    slug: "wb-1-property-description",
    name: "WB-1 property description",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [notes("Lines 2-5 Property Description", 5)],
    partOf: ["wb-1-residential-listing"],
  },
  {
    slug: "wb-1-included-items",
    name: "WB-1 included items",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [notes("Lines 6-10 Included Items", 6)],
    partOf: ["wb-1-residential-listing"],
  },
  {
    slug: "wb-1-not-included-items",
    name: "WB-1 not included in list price",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [notes("Lines 11-15 Not Included in List Price", 6)],
    partOf: ["wb-1-residential-listing"],
  },
  {
    slug: "fixtures",
    name: "Fixtures",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "both",
    examCategoryCodes: FORMS,
    citations: [
      book("Important Terminology", 43, 47),
      notes("Lines 191-204 Fixtures", 7),
    ],
    prerequisites: ["wb-1-residential-listing"],
  },
  {
    slug: "wb-1-list-price",
    name: "WB-1 list price",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [notes("Line 16 List Price", 9)],
    partOf: ["wb-1-residential-listing"],
  },
  {
    slug: "wb-1-marketing",
    name: "WB-1 marketing",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [notes("Lines 17-29 Marketing", 9)],
    partOf: ["wb-1-residential-listing"],
  },
  {
    slug: "wb-1-commission",
    name: "WB-1 commission",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY_AND_FORMS,
    citations: [notes("Lines 30-56 Commission", 10)],
    partOf: ["wb-1-residential-listing"],
    prerequisites: ["commission"],
  },
  {
    slug: "wb-1-compensation-to-others",
    name: "WB-1 compensation to others",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY_AND_FORMS,
    citations: [notes("Lines 57-62 Compensation to Others", 12)],
    partOf: ["wb-1-residential-listing"],
    prerequisites: ["wb-1-commission"],
  },
  {
    slug: "wb-1-agency-choices",
    name: "WB-1 agency choices",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY_AND_FORMS,
    citations: [
      notes("Lines 122-134 Agency Choices", 15),
      notes("Lines 105-121 Multiple Representation Relationship", 14),
    ],
    partOf: ["wb-1-residential-listing"],
    prerequisites: ["multiple-representation"],
  },
  {
    slug: "protected-buyer",
    name: "Protected buyer",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY_AND_FORMS,
    citations: [notes("Lines 215-229 Protected Buyer", 18)],
    partOf: ["wb-1-residential-listing"],
  },
  {
    slug: "extension-of-listing",
    name: "Extension of listing",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [notes("Lines 230-234 Extension of Listing", 19)],
    partOf: ["wb-1-residential-listing"],
  },
  {
    slug: "termination-of-listing",
    name: "Termination of listing (WB-1)",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY_AND_FORMS,
    citations: [notes("Lines 273-281 Termination of Listing", 24)],
    partOf: ["wb-1-residential-listing"],
    prerequisites: ["termination-of-agency"],
  },
  {
    slug: "wb-1-earnest-money",
    name: "WB-1 earnest money",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [notes("Lines 282-289 Earnest Money", 24)],
    partOf: ["wb-1-residential-listing"],
  },
  {
    slug: "wb-1-delivery",
    name: "WB-1 delivery",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [notes("Lines 290-312 Delivery", 25)],
    partOf: ["wb-1-residential-listing"],
  },
  {
    slug: "wb-1-term-of-contract",
    name: "WB-1 term of the contract",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [notes("Lines 338-340 Term of the Contract", 27)],
    partOf: ["wb-1-residential-listing"],
  },
  {
    slug: "wb-4-condo-listing",
    name: "WB-4 Residential Condominium Listing Contract",
    chapterNumber: 3,
    group: "agency-agreements",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY_AND_FORMS,
    citations: [
      book("WB-4 RESIDENTIAL CONDOMINIUM LISTING CONTRACT", 63, 67),
      notes("WB-4 Residential Condominium Listing Contract", 28),
    ],
    partOf: ["agency-agreements"],
    prerequisites: ["wb-1-residential-listing"],
  },
  {
    slug: "limited-common-elements",
    name: "Limited common elements",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [notes("Lines 19-20 Limited Common Elements", 29)],
    partOf: ["wb-4-condo-listing"],
  },
  {
    slug: "association-fee",
    name: "Association fee",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [
      notes("Line 24 Association Fee", 30),
      notes("Line 21-26 Storage Unit/ Parking/Association Fee/ Right of First Refusal", 29),
    ],
    partOf: ["wb-4-condo-listing"],
  },
  {
    slug: "condominium-disclosure-materials",
    name: "Condominium disclosure materials",
    chapterNumber: 3,
    group: "listing-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [notes("Lines 223-260 Condominium Disclosure Materials", 31)],
    partOf: ["wb-4-condo-listing"],
  },
  {
    slug: "wb-36-buyer-agency",
    name: "WB-36 Buyer Agency Agreement",
    chapterNumber: 3,
    group: "agency-agreements",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY_AND_FORMS,
    citations: [
      book("WB-36 BUYER AGENCY AGREEMENT", 67, 71),
      notes("WB-36 Buyer Agency Agreement", 33),
    ],
    partOf: ["agency-agreements"],
    prerequisites: ["buyer-agency-agreements", "agency-agreements"],
  },
  {
    slug: "wb-36-excluded-properties",
    name: "WB-36 excluded properties",
    chapterNumber: 3,
    group: "buyer-agency-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [
      notes("Lines 14-17 Excluded Properties", 35),
      notes("Identifying the Properties Covered by the Buyer Agency", 35),
    ],
    partOf: ["wb-36-buyer-agency"],
  },
  {
    slug: "wb-36-compensation",
    name: "WB-36 compensation",
    chapterNumber: 3,
    group: "buyer-agency-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY_AND_FORMS,
    citations: [notes("Lines 30-60 Compensation", 37)],
    partOf: ["wb-36-buyer-agency"],
    prerequisites: ["commission"],
  },
  {
    slug: "protected-property",
    name: "Protected property",
    chapterNumber: 3,
    group: "buyer-agency-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: AGENCY_AND_FORMS,
    citations: [notes("Lines 217-225 Protected Property", 39)],
    partOf: ["wb-36-buyer-agency"],
  },
  {
    slug: "extension-of-agreement-term",
    name: "Extension of agreement term (WB-36)",
    chapterNumber: 3,
    group: "buyer-agency-forms",
    jurisdictionScope: "wi",
    examCategoryCodes: FORMS,
    citations: [notes("Lines 243-248 Extension of Agreement Term", 40)],
    partOf: ["wb-36-buyer-agency"],
  },
];

export const CHAPTER_3_CONFUSION_PAIRS: readonly ConfusionPairSeed[] = [
  {
    a: "buyer-in-transaction",
    b: "seller-in-transaction",
    reason: "Chapter 3 notes list the buyer and the seller as separate transaction parties.",
  },
  {
    a: "wb-1-included-items",
    b: "wb-1-not-included-items",
    reason: "WB-1 notes separate Included Items from Not Included in List Price.",
  },
  {
    a: "protected-buyer",
    b: "extension-of-listing",
    reason: "WB-1 notes list Protected Buyer and Extension of Listing as separate headings.",
  },
  {
    a: "wb-1-residential-listing",
    b: "wb-4-condo-listing",
    reason: "Chapter 3 has separate WB-1 residential and WB-4 condominium listing contract headings.",
  },
  {
    a: "wb-1-residential-listing",
    b: "wb-36-buyer-agency",
    reason: "Chapter 3 separates the seller-side WB-1 listing from the buyer-side WB-36 agreement.",
  },
  {
    a: "protected-buyer",
    b: "protected-property",
    reason: "Protected buyer is a WB-1 listing heading; protected property is a WB-36 buyer-agency heading.",
  },
  {
    a: "extension-of-listing",
    b: "extension-of-agreement-term",
    reason: "WB-1 Extension of Listing is not the same heading as WB-36 Extension of Agreement Term.",
  },
  {
    a: "limited-common-elements",
    b: "association-fee",
    reason: "WB-4 notes treat limited common elements and association fee as separate condominium headings.",
  },
];

export const WI_SCOPED_CHAPTER_3_SLUGS = CHAPTER_3_CONCEPTS.filter(
  (concept) => concept.jurisdictionScope === "wi",
).map((concept) => concept.slug);
