import type { AssetSeed } from "./assets";

/**
 * Hand-authored Chapter 4 (Disclosure Obligations) teaching units.
 * Original language plus heading citations. No invented statutes or fees.
 */
export const PHASE4_CH4_ASSETS: readonly AssetSeed[] = [
  {
    slug: "ch4-disclosure-explanation",
    kind: "explanation",
    informationClass: "general_explanation",
    conceptSlug: "disclosure",
    title: "Disclosure",
    body: "Chapter 4 opens with Disclosure, then Liability and Advertising, before the disclosure-obligation headings. Keep this chapter’s property-disclosure path separate from Chapter 1’s agency-disclosure headings.",
    citationSlugs: ["disclosure"],
  },
  {
    slug: "ch4-disclosure-obligations-explanation",
    kind: "explanation",
    informationClass: "general_explanation",
    conceptSlug: "disclosure-obligations",
    title: "Disclosure obligations",
    body: "Disclosure Obligations is the Chapter 4 bridge into owner disclosure, as-is sales, licensee disclosure, condominium disclosure, and environmental concerns. Do not invent Wisconsin deadlines from the heading alone.",
    citationSlugs: ["disclosure-obligations"],
  },
  {
    slug: "ch4-owner-vs-licensee-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "disclosure-by-owners", b: "licensee-disclosure-obligations" },
    title: "Owner disclosure vs licensee disclosure",
    body: "Chapter 4 separates Disclosure by Owners of Real Estate from Licensee Disclosure Obligations. Repair by asking whose duty the item is testing — the owner’s disclosure path or the licensee’s — before mixing them.",
    citationSlugs: ["disclosure-by-owners", "licensee-disclosure-obligations"],
  },
  {
    slug: "ch4-owner-vs-licensee-teachback",
    kind: "teachback_prompt",
    informationClass: "course_sourced",
    pair: { a: "disclosure-by-owners", b: "licensee-disclosure-obligations" },
    title: "Say owner vs licensee disclosure",
    body: "Explain how Chapter 4 lists owner disclosure and licensee disclosure as separate headings. One sentence each. Do not invent statute numbers.",
    citationSlugs: ["disclosure-by-owners", "licensee-disclosure-obligations"],
  },
  {
    slug: "ch4-recr-completion-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "seller-completion-of-recr", b: "amending-an-recr" },
    title: "Completing vs amending an RECR",
    body: "Chapter 4 notes list Seller Completion of an RECR and Amending an RECR as separate headings. Repair by asking whether the item is about first completing the report or later amending it.",
    citationSlugs: ["seller-completion-of-recr", "amending-an-recr"],
  },
  {
    slug: "ch4-asis-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "as-is-sales", b: "disclosure-by-owners" },
    title: "As-is sales vs owner disclosure",
    body: "Chapter 4 has a separate “As-is” Sales heading next to Disclosure by Owners of Real Estate. They are related, not interchangeable. Read both headings; do not invent that as-is erases every disclosure duty.",
    citationSlugs: ["as-is-sales", "disclosure-by-owners"],
  },
  {
    slug: "ch4-rescission-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "buyer-rescission", b: "amending-an-recr" },
    title: "Buyer rescission vs amending an RECR",
    body: "Chapter 4 notes distinguish Buyer Rescission from Amending an RECR. Repair by asking whether the item is about a buyer’s rescission path or an amendment to the report.",
    citationSlugs: ["buyer-rescission", "amending-an-recr"],
  },
  {
    slug: "ch4-condo-vs-owner-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "condominium-disclosure-requirements", b: "disclosure-by-owners" },
    title: "Condo disclosure vs owner RECR disclosure",
    body: "Chapter 4 lists Condominium Disclosure Requirements separately from Disclosure by Owners of Real Estate. Condo packages and RECR owner disclosure are different headings — do not collapse them.",
    citationSlugs: ["condominium-disclosure-requirements", "disclosure-by-owners"],
  },
  {
    slug: "ch4-condo-docs-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "executive-summary", b: "condominium-documents" },
    title: "Executive summary vs condominium documents",
    body: "Chapter 4 notes list Executive Summary and Condominium Documents as separate condominium disclosure headings. Repair by naming which heading the item is testing.",
    citationSlugs: ["executive-summary", "condominium-documents"],
  },
  {
    slug: "ch4-environmental-explanation",
    kind: "explanation",
    informationClass: "general_explanation",
    conceptSlug: "environmental-concerns",
    title: "Environmental concerns",
    body: "Environmental Concerns closes Chapter 4 with its own book heading. Notes then split lead-based paint, UST, asbestos, vermiculite, radon, mold, and water quality. Keep the parent heading when an item names a hazard subtype.",
    citationSlugs: ["environmental-concerns"],
  },
  {
    slug: "ch4-lead-asbestos-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "lead-based-paint", b: "asbestos" },
    title: "Lead-based paint vs asbestos",
    body: "Chapter 4 notes list Lead-Based Paint and Asbestos as separate environmental headings. Repair by naming the hazard heading — do not invent federal pamphlet text or statute numbers here.",
    citationSlugs: ["lead-based-paint", "asbestos"],
  },
  {
    slug: "ch4-radon-mold-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "radon", b: "mold" },
    title: "Radon vs mold",
    body: "Chapter 4 notes list Radon and Mold as separate environmental concern headings. They are not interchangeable labels under Environmental Concerns.",
    citationSlugs: ["radon", "mold"],
  },
  {
    slug: "ch4-owner-licensee-recall",
    kind: "recall_prompt",
    informationClass: "course_sourced",
    pair: { a: "disclosure-by-owners", b: "licensee-disclosure-obligations" },
    title: "Recall: whose disclosure heading?",
    body: "An item asks about a licensee’s disclosure duty on property condition. Which Chapter 4 heading is that — Disclosure by Owners or Licensee Disclosure Obligations — and what is the sibling heading?",
    citationSlugs: ["disclosure-by-owners", "licensee-disclosure-obligations"],
  },
  {
    slug: "ch4-asis-recall",
    kind: "recall_prompt",
    informationClass: "course_sourced",
    pair: { a: "as-is-sales", b: "disclosure-by-owners" },
    title: "Recall: as-is vs owner disclosure",
    body: "A seller markets a property as-is. Name the Chapter 4 as-is heading and the separate owner-disclosure heading you still need to keep distinct.",
    citationSlugs: ["as-is-sales", "disclosure-by-owners"],
  },
  {
    slug: "ch4-condo-teachback",
    kind: "teachback_prompt",
    informationClass: "course_sourced",
    pair: { a: "executive-summary", b: "condominium-documents" },
    title: "Say the condo disclosure split",
    body: "Explain how Chapter 4 separates Executive Summary from Condominium Documents under condominium disclosure requirements. Do not invent delivery deadlines beyond those headings.",
    citationSlugs: ["executive-summary", "condominium-documents"],
  },
];

export const PHASE4_CH4_SESSION_STEPS: readonly {
  assetSlug: string;
  kind: "learn" | "repair" | "teachback" | "recall";
  reasonCodes: readonly string[];
}[] = [
  { assetSlug: "ch4-disclosure-explanation", kind: "learn", reasonCodes: ["exam_weight_disclosures", "chapter_4"] },
  { assetSlug: "ch4-disclosure-obligations-explanation", kind: "learn", reasonCodes: ["exam_weight_disclosures"] },
  { assetSlug: "ch4-owner-vs-licensee-comparison", kind: "repair", reasonCodes: ["confusion_pair", "wisconsin_heading"] },
  { assetSlug: "ch4-owner-vs-licensee-teachback", kind: "teachback", reasonCodes: ["confusion_pair"] },
  { assetSlug: "ch4-recr-completion-comparison", kind: "repair", reasonCodes: ["confusion_pair", "wisconsin_heading"] },
  { assetSlug: "ch4-asis-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch4-rescission-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch4-condo-vs-owner-comparison", kind: "repair", reasonCodes: ["confusion_pair", "wisconsin_heading"] },
  { assetSlug: "ch4-condo-docs-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch4-condo-teachback", kind: "teachback", reasonCodes: ["confusion_pair"] },
  { assetSlug: "ch4-environmental-explanation", kind: "learn", reasonCodes: ["exam_weight_disclosures"] },
  { assetSlug: "ch4-lead-asbestos-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch4-radon-mold-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch4-owner-licensee-recall", kind: "recall", reasonCodes: ["retrieval", "wisconsin_heading"] },
  { assetSlug: "ch4-asis-recall", kind: "recall", reasonCodes: ["retrieval"] },
];
