import type { AssetSeed } from "./assets";

/**
 * Hand-authored Chapter 3 (Agency Agreements) teaching units.
 * Original language plus heading citations. No invented statutes or fees.
 */
export const PHASE4_CH3_ASSETS: readonly AssetSeed[] = [
  {
    slug: "ch3-transaction-explanation",
    kind: "explanation",
    informationClass: "general_explanation",
    conceptSlug: "real-estate-transaction",
    title: "The real estate transaction",
    body: "Chapter 3 opens with The Real Estate Transaction before the approved forms. Notes split buyer, seller, and closing under that parent idea. Keep the transaction map in mind when you later open WB-1 or WB-36.",
    citationSlugs: ["real-estate-transaction"],
  },
  {
    slug: "ch3-buyer-seller-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "buyer-in-transaction", b: "seller-in-transaction" },
    title: "Buyer vs seller in the transaction",
    body: "Chapter 3 notes list The buyer and The seller as separate headings under the transaction. Repair by asking which side of the deal the item is describing before you jump to a form number.",
    citationSlugs: ["buyer-in-transaction", "seller-in-transaction"],
  },
  {
    slug: "ch3-agency-agreements-explanation",
    kind: "explanation",
    informationClass: "general_explanation",
    conceptSlug: "agency-agreements",
    title: "Agency agreements",
    body: "Agency Agreements is the Chapter 3 bridge from Chapter 2 contract types into Wisconsin approved forms. The notes then open WB-1, WB-4, and WB-36. Do not invent fee amounts or statute cites from the form titles alone.",
    citationSlugs: ["agency-agreements"],
  },
  {
    slug: "ch3-wb1-explanation",
    kind: "explanation",
    informationClass: "course_sourced",
    conceptSlug: "wb-1-residential-listing",
    title: "WB-1 Residential Listing Contract",
    body: "WB-1 is the residential exclusive-right-to-sell listing contract heading in both the book and the notes. It is the seller-side approved form path in this chapter. Later line headings (commission, protected buyer, termination) sit under this form.",
    citationSlugs: ["wb-1-residential-listing"],
  },
  {
    slug: "ch3-included-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "wb-1-included-items", b: "wb-1-not-included-items" },
    title: "Included vs not included (WB-1)",
    body: "WB-1 notes separate Included Items from Not Included in List Price. Repair by asking whether the item stays with the property under the included heading or is carved out under not included — then read fixtures as its own related heading.",
    citationSlugs: ["wb-1-included-items", "wb-1-not-included-items", "fixtures"],
  },
  {
    slug: "ch3-fixtures-simple",
    kind: "simple_language",
    informationClass: "general_explanation",
    conceptSlug: "fixtures",
    title: "Fixtures in plain language",
    body: "Fixtures has its own Important Terminology and WB-1 line heading. On exam items about what conveys with the sale, point to that heading rather than inventing a personal-property rule here.",
    citationSlugs: ["fixtures"],
  },
  {
    slug: "ch3-protected-buyer-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "protected-buyer", b: "extension-of-listing" },
    title: "Protected buyer vs extension of listing",
    body: "WB-1 notes list Protected Buyer and Extension of Listing as separate headings. They are related timing ideas, not interchangeable labels. Repair by naming which heading the item is actually testing.",
    citationSlugs: ["protected-buyer", "extension-of-listing"],
  },
  {
    slug: "ch3-protected-buyer-teachback",
    kind: "teachback_prompt",
    informationClass: "course_sourced",
    pair: { a: "protected-buyer", b: "extension-of-listing" },
    title: "Say protected buyer vs extension",
    body: "Explain, without looking, how Chapter 3 separates Protected Buyer from Extension of Listing on WB-1. One sentence each. Do not invent Wisconsin dollar amounts.",
    citationSlugs: ["protected-buyer", "extension-of-listing"],
  },
  {
    slug: "ch3-wb1-wb4-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "wb-1-residential-listing", b: "wb-4-condo-listing" },
    title: "WB-1 vs WB-4",
    body: "Chapter 3 has separate headings for WB-1 Residential Listing Contract and WB-4 Residential Condominium Listing Contract. WB-4 adds condominium-specific headings such as limited common elements and condominium disclosure materials. Do not treat WB-4 as a rename of WB-1.",
    citationSlugs: ["wb-1-residential-listing", "wb-4-condo-listing"],
  },
  {
    slug: "ch3-condo-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "limited-common-elements", b: "association-fee" },
    title: "Limited common elements vs association fee",
    body: "WB-4 notes list Limited Common Elements and Association Fee as separate condominium headings. Repair by asking whether the item is about a physical limited element or about the association fee line.",
    citationSlugs: ["limited-common-elements", "association-fee"],
  },
  {
    slug: "ch3-wb1-wb36-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "wb-1-residential-listing", b: "wb-36-buyer-agency" },
    title: "WB-1 vs WB-36",
    body: "WB-1 is the seller-side residential listing form; WB-36 is the Buyer Agency Agreement. Chapter 3 keeps those as separate form headings. Repair by asking which side of the transaction the written agency agreement covers.",
    citationSlugs: ["wb-1-residential-listing", "wb-36-buyer-agency"],
  },
  {
    slug: "ch3-wb36-explanation",
    kind: "explanation",
    informationClass: "course_sourced",
    conceptSlug: "wb-36-buyer-agency",
    title: "WB-36 Buyer Agency Agreement",
    body: "WB-36 is the Chapter 3 buyer-agency approved form. Notes cover exclusive authority, excluded properties, compensation, protected property, and extension of agreement term. Cite those headings; do not invent form-line text beyond them.",
    citationSlugs: ["wb-36-buyer-agency"],
  },
  {
    slug: "ch3-protected-pair-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "protected-buyer", b: "protected-property" },
    title: "Protected buyer vs protected property",
    body: "Protected buyer is a WB-1 listing heading. Protected property is a WB-36 buyer-agency heading. Same word 'protected,' different forms and sides of the deal. Do not swap them.",
    citationSlugs: ["protected-buyer", "protected-property"],
  },
  {
    slug: "ch3-extension-pair-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "extension-of-listing", b: "extension-of-agreement-term" },
    title: "Extension of listing vs extension of agreement term",
    body: "WB-1 Extension of Listing is not WB-36 Extension of Agreement Term. Repair by naming the form first, then the extension heading that belongs to that form.",
    citationSlugs: ["extension-of-listing", "extension-of-agreement-term"],
  },
  {
    slug: "ch3-wb1-wb36-teachback",
    kind: "teachback_prompt",
    informationClass: "course_sourced",
    pair: { a: "wb-1-residential-listing", b: "wb-36-buyer-agency" },
    title: "Say WB-1 vs WB-36",
    body: "Explain which approved form is the seller-side residential listing and which is the buyer agency agreement in Chapter 3. Say one reason swapping them would change an item.",
    citationSlugs: ["wb-1-residential-listing", "wb-36-buyer-agency"],
  },
  {
    slug: "ch3-protected-recall",
    kind: "recall_prompt",
    informationClass: "course_sourced",
    pair: { a: "protected-buyer", b: "protected-property" },
    title: "Recall: which protected heading?",
    body: "An item mentions a protected buyer under a listing. Is that the WB-1 Protected Buyer heading or the WB-36 Protected Property heading — and what is the sibling heading on the other form?",
    citationSlugs: ["protected-buyer", "protected-property"],
  },
  {
    slug: "ch3-forms-recall",
    kind: "recall_prompt",
    informationClass: "course_sourced",
    pair: { a: "wb-1-residential-listing", b: "wb-4-condo-listing" },
    title: "Recall: WB-1 or WB-4?",
    body: "A condominium listing needs association fee and limited common element headings. Which Chapter 3 form heading is that — WB-1 or WB-4 — and what is the ordinary residential listing sibling?",
    citationSlugs: ["wb-1-residential-listing", "wb-4-condo-listing"],
  },
];

export const PHASE4_CH3_SESSION_STEPS: readonly {
  assetSlug: string;
  kind: "learn" | "repair" | "teachback" | "recall";
  reasonCodes: readonly string[];
}[] = [
  { assetSlug: "ch3-transaction-explanation", kind: "learn", reasonCodes: ["exam_weight_agency", "chapter_3"] },
  { assetSlug: "ch3-buyer-seller-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch3-agency-agreements-explanation", kind: "learn", reasonCodes: ["exam_weight_agency", "exam_weight_forms"] },
  { assetSlug: "ch3-wb1-explanation", kind: "learn", reasonCodes: ["exam_weight_forms", "wisconsin_heading"] },
  { assetSlug: "ch3-included-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch3-fixtures-simple", kind: "learn", reasonCodes: ["exam_weight_forms", "modality_simple"] },
  { assetSlug: "ch3-protected-buyer-comparison", kind: "repair", reasonCodes: ["confusion_pair", "wisconsin_heading"] },
  { assetSlug: "ch3-protected-buyer-teachback", kind: "teachback", reasonCodes: ["confusion_pair"] },
  { assetSlug: "ch3-wb1-wb4-comparison", kind: "repair", reasonCodes: ["confusion_pair", "wisconsin_heading"] },
  { assetSlug: "ch3-condo-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch3-wb1-wb36-comparison", kind: "repair", reasonCodes: ["confusion_pair", "wisconsin_heading"] },
  { assetSlug: "ch3-wb36-explanation", kind: "learn", reasonCodes: ["exam_weight_forms", "wisconsin_heading"] },
  { assetSlug: "ch3-protected-pair-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch3-extension-pair-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch3-wb1-wb36-teachback", kind: "teachback", reasonCodes: ["confusion_pair"] },
  { assetSlug: "ch3-protected-recall", kind: "recall", reasonCodes: ["retrieval"] },
  { assetSlug: "ch3-forms-recall", kind: "recall", reasonCodes: ["retrieval", "wisconsin_heading"] },
];
