import type { AssetSeed } from "./assets";

/**
 * Hand-authored Chapter 2 (Agency Issues) teaching units.
 * Original language plus heading citations. No invented statutes or fees.
 */
export const PHASE4_CH2_ASSETS: readonly AssetSeed[] = [
  {
    slug: "ch2-creation-explanation",
    kind: "explanation",
    informationClass: "general_explanation",
    conceptSlug: "creation-of-agency",
    title: "The creation of agency",
    body: "Chapter 2 opens with The Creation of Agency. Before listing contracts or commission, the course asks how the agency relationship starts. Later headings under Important Terminology name express and implied paths — keep creation as the parent idea.",
    citationSlugs: ["creation-of-agency"],
  },
  {
    slug: "ch2-creation-simple",
    kind: "simple_language",
    informationClass: "general_explanation",
    conceptSlug: "creation-of-agency",
    title: "Creation in plain language",
    body: "Agency does not appear from thin air. Chapter 2 has a creation heading, then terms for how that relationship can be expressed or implied. Do not invent Wisconsin procedure beyond those headings.",
    citationSlugs: ["creation-of-agency"],
  },
  {
    slug: "ch2-express-implied-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "express-agency", b: "implied-agency" },
    title: "Express vs implied agency",
    body: "Chapter 2 Important Terminology lists express agency and implied agency as separate creation terms. Repair the pair by asking: was the agency spelled out, or did conduct create it? Do not collapse them into one 'agency exists' answer.",
    citationSlugs: ["express-agency", "implied-agency"],
  },
  {
    slug: "ch2-express-implied-teachback",
    kind: "teachback_prompt",
    informationClass: "course_sourced",
    pair: { a: "express-agency", b: "implied-agency" },
    title: "Say express vs implied",
    body: "Without looking, explain how Chapter 2 separates express agency from implied agency. One sentence each. Do not invent extra Wisconsin statutes.",
    citationSlugs: ["express-agency", "implied-agency"],
  },
  {
    slug: "ch2-special-general-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "special-agency", b: "general-agency" },
    title: "Special vs general agency",
    body: "Types of Agency Contracts and Important Terminology treat special agency and general agency as separate terms. Repair by asking how broad the agent's authority is under each heading — not by inventing a duty list.",
    citationSlugs: ["special-agency", "general-agency"],
  },
  {
    slug: "ch2-listing-contracts-explanation",
    kind: "explanation",
    informationClass: "general_explanation",
    conceptSlug: "listing-contracts",
    title: "Listing contracts",
    body: "Chapter 2 has a Listing Contracts heading after types of agency contracts. The notes then split exclusive right to sell, exclusive agency, open, one-party, and net. Keep the parent heading when an item names a listing type.",
    citationSlugs: ["listing-contracts"],
  },
  {
    slug: "ch2-exclusive-listings-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "exclusive-agency-listing", b: "exclusive-right-to-sell-listing" },
    title: "Exclusive agency vs exclusive right to sell",
    body: "Chapter 2 notes list Exclusive Agency Listing Contract and Exclusive Right to Sell Listing Contract as separate headings. They are not interchangeable. Repair by asking who can sell without owing the firm — the seller alone under exclusive agency, versus the firm still owed under exclusive right to sell when the seller finds the buyer. Read the sourced headings; do not invent fee amounts.",
    citationSlugs: ["exclusive-agency-listing", "exclusive-right-to-sell-listing"],
  },
  {
    slug: "ch2-exclusive-listings-teachback",
    kind: "teachback_prompt",
    informationClass: "course_sourced",
    pair: { a: "exclusive-agency-listing", b: "exclusive-right-to-sell-listing" },
    title: "Say the listing pair",
    body: "Explain the difference between exclusive agency and exclusive right to sell as Chapter 2 lists them. Say why swapping the labels would change an Agency item.",
    citationSlugs: ["exclusive-agency-listing", "exclusive-right-to-sell-listing"],
  },
  {
    slug: "ch2-open-vs-exclusive-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "open-listing-contract", b: "exclusive-right-to-sell-listing" },
    title: "Open listing vs exclusive right to sell",
    body: "Chapter 2 notes distinguish an Open Listing Contract from an Exclusive Right to Sell Listing Contract. An open listing is not the exclusive-right heading. Keep those names separate when an item describes how many firms may market the property.",
    citationSlugs: ["open-listing-contract", "exclusive-right-to-sell-listing"],
  },
  {
    slug: "ch2-listing-buyer-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "listing-contracts", b: "buyer-agency-agreements" },
    title: "Listing contracts vs buyer agency agreements",
    body: "Chapter 2 has separate headings for Listing Contracts and Buyer Agency Agreements. Repair by asking which side of the deal the written agency contract covers — seller-side listing versus buyer-side agreement — before naming a subtype.",
    citationSlugs: ["listing-contracts", "buyer-agency-agreements"],
  },
  {
    slug: "ch2-locate-negotiate-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "exclusive-right-to-locate", b: "exclusive-right-to-negotiate" },
    title: "Locate vs negotiate (buyer agency)",
    body: "Chapter 2 notes split buyer agency into Exclusive Right to Locate and Exclusive Right to Negotiate (and a combined locate-and-negotiate heading). Repair by asking whether the authority is to find property, to negotiate, or both — not by inventing Wisconsin form numbers beyond the payment headings later.",
    citationSlugs: ["exclusive-right-to-locate", "exclusive-right-to-negotiate"],
  },
  {
    slug: "ch2-termination-explanation",
    kind: "explanation",
    informationClass: "general_explanation",
    conceptSlug: "termination-of-agency",
    title: "Termination of agency",
    body: "Chapter 2 has a Termination of Agency heading after the contract types. Creation and termination are separate headings. When an item asks how the relationship ends, point to termination — not to a listing subtype.",
    citationSlugs: ["termination-of-agency"],
  },
  {
    slug: "ch2-damages-rescission-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "damages", b: "rescission" },
    title: "Damages vs rescission",
    body: "Under Remedies for Breach of an Agency Agreement, Important Terminology lists damages and rescission as separate terms. Repair by asking whether the remedy is money for the breach or unwinding the agreement — do not invent dollar amounts.",
    citationSlugs: ["damages", "rescission"],
  },
  {
    slug: "ch2-antitrust-explanation",
    kind: "explanation",
    informationClass: "general_explanation",
    conceptSlug: "antitrust-laws",
    title: "Antitrust laws",
    body: "Chapter 2 places Antitrust Laws next to Commission. Price fixing and group boycott appear as separate Important Terminology terms under that antitrust discussion. This sitting maps those headings to exam outline IX where the catalog joins them — still no invented statutes.",
    citationSlugs: ["antitrust-laws"],
  },
  {
    slug: "ch2-price-boycott-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "price-fixing", b: "group-boycott" },
    title: "Price fixing vs group boycott",
    body: "Chapter 2 Important Terminology lists price fixing and group boycott as separate antitrust terms. Repair by naming which heading fits: agreeing on rates versus refusing to deal with a competitor as a group. Do not invent Wisconsin fee schedules.",
    citationSlugs: ["price-fixing", "group-boycott"],
  },
  {
    slug: "ch2-cooperating-inhouse-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "commission-cooperating-firms", b: "commission-in-house-sale" },
    title: "Cooperating firms vs in-house sale commission",
    body: "Chapter 2 has separate headings for Commission in a Sale with Cooperating Firms and Commission in an In-House Sale. Repair by asking whether another firm is in the deal or the same firm handles both sides — then read the matching heading. Do not invent split percentages.",
    citationSlugs: ["commission-cooperating-firms", "commission-in-house-sale"],
  },
  {
    slug: "ch2-payment-firms-comparison",
    kind: "comparison",
    informationClass: "course_sourced",
    pair: { a: "payment-of-listing-firm", b: "payment-of-buyers-firm" },
    title: "Payment of listing firm vs buyer’s firm",
    body: "Chapter 2 ends with Payment of a Listing Firm and Payment of a Buyer’s Firm as separate Wisconsin-scoped headings. Repair by asking which firm’s payment heading the item is testing. Cite those headings; do not invent WB form line text here.",
    citationSlugs: ["payment-of-listing-firm", "payment-of-buyers-firm"],
  },
  {
    slug: "ch2-exclusive-listings-recall",
    kind: "recall_prompt",
    informationClass: "course_sourced",
    pair: { a: "exclusive-agency-listing", b: "exclusive-right-to-sell-listing" },
    title: "Recall: which exclusive listing?",
    body: "A seller finds their own buyer. Under which Chapter 2 listing heading might the firm still be owed a commission, and which heading treats the seller’s own sale differently? Name both headings.",
    citationSlugs: ["exclusive-agency-listing", "exclusive-right-to-sell-listing"],
  },
  {
    slug: "ch2-payment-recall",
    kind: "recall_prompt",
    informationClass: "course_sourced",
    pair: { a: "payment-of-listing-firm", b: "payment-of-buyers-firm" },
    title: "Recall: whose payment heading?",
    body: "An item asks when the listing firm is paid. Which Chapter 2 heading is that — Payment of a Listing Firm or Payment of a Buyer’s Firm — and what is the sibling heading for the other firm?",
    citationSlugs: ["payment-of-listing-firm", "payment-of-buyers-firm"],
  },
];

export const PHASE4_CH2_SESSION_STEPS: readonly {
  assetSlug: string;
  kind: "learn" | "repair" | "teachback" | "recall";
  reasonCodes: readonly string[];
}[] = [
  { assetSlug: "ch2-creation-explanation", kind: "learn", reasonCodes: ["exam_weight_agency", "chapter_2"] },
  { assetSlug: "ch2-creation-simple", kind: "learn", reasonCodes: ["exam_weight_agency", "modality_simple"] },
  { assetSlug: "ch2-express-implied-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch2-express-implied-teachback", kind: "teachback", reasonCodes: ["confusion_pair"] },
  { assetSlug: "ch2-special-general-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch2-listing-contracts-explanation", kind: "learn", reasonCodes: ["exam_weight_agency"] },
  { assetSlug: "ch2-exclusive-listings-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch2-exclusive-listings-teachback", kind: "teachback", reasonCodes: ["confusion_pair"] },
  { assetSlug: "ch2-open-vs-exclusive-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch2-listing-buyer-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch2-locate-negotiate-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch2-termination-explanation", kind: "learn", reasonCodes: ["exam_weight_agency"] },
  { assetSlug: "ch2-damages-rescission-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch2-antitrust-explanation", kind: "learn", reasonCodes: ["exam_weight_antitrust", "chapter_2"] },
  { assetSlug: "ch2-price-boycott-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch2-cooperating-inhouse-comparison", kind: "repair", reasonCodes: ["confusion_pair", "seed"] },
  { assetSlug: "ch2-payment-firms-comparison", kind: "repair", reasonCodes: ["confusion_pair", "wisconsin_heading"] },
  { assetSlug: "ch2-exclusive-listings-recall", kind: "recall", reasonCodes: ["retrieval"] },
  { assetSlug: "ch2-payment-recall", kind: "recall", reasonCodes: ["retrieval", "wisconsin_heading"] },
];
